# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_add_data.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(896, 1987)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 40, 731, 131))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(30, 210, 731, 131))
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_4.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_5.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_6.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(30, 380, 731, 131))
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_3.setObjectName("label_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox_7 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_7.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_8 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_8.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_9 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_9.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(30, 550, 731, 131))
        self.widget_4.setObjectName("widget_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.comboBox_10 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_10.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_11 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_11.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_12 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_12.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(30, 720, 731, 131))
        self.widget_5.setObjectName("widget_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_13.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.comboBox_13 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_13.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_14 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_14.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_15 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_15.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_15.setObjectName("comboBox_15")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_5.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setGeometry(QtCore.QRect(30, 890, 731, 131))
        self.widget_6.setObjectName("widget_6")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_6.setObjectName("label_6")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_16.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.comboBox_16 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_16.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_17 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_17.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_18 = QtWidgets.QComboBox(self.widget_6)
        self.comboBox_18.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_18.setObjectName("comboBox_18")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_17.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_18.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_6.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.widget_7 = QtWidgets.QWidget(Form)
        self.widget_7.setGeometry(QtCore.QRect(30, 1060, 731, 131))
        self.widget_7.setObjectName("widget_7")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_7.setObjectName("label_7")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_19.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.comboBox_19 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_19.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_20 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_20.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_21 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_21.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_21.setObjectName("comboBox_21")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_20.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_21.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_7.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.widget_8 = QtWidgets.QWidget(Form)
        self.widget_8.setGeometry(QtCore.QRect(30, 1230, 731, 131))
        self.widget_8.setObjectName("widget_8")
        self.label_8 = QtWidgets.QLabel(self.widget_8)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_8.setObjectName("label_8")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_22.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.comboBox_22 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_22.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_23 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_23.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_24 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_24.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_24.setObjectName("comboBox_24")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_23.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_24.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_8.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.widget_9 = QtWidgets.QWidget(Form)
        self.widget_9.setGeometry(QtCore.QRect(30, 1400, 731, 131))
        self.widget_9.setObjectName("widget_9")
        self.label_9 = QtWidgets.QLabel(self.widget_9)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_9.setObjectName("label_9")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_25.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.comboBox_25 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_25.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_26 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_26.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_27 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_27.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_27.setObjectName("comboBox_27")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_26.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_27.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_9.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.widget_10 = QtWidgets.QWidget(Form)
        self.widget_10.setGeometry(QtCore.QRect(30, 1570, 731, 131))
        self.widget_10.setObjectName("widget_10")
        self.label_10 = QtWidgets.QLabel(self.widget_10)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_10.setObjectName("label_10")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_28.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.comboBox_28 = QtWidgets.QComboBox(self.widget_10)
        self.comboBox_28.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_29 = QtWidgets.QComboBox(self.widget_10)
        self.comboBox_29.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_30 = QtWidgets.QComboBox(self.widget_10)
        self.comboBox_30.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_30.setObjectName("comboBox_30")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_29.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_30.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_10.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        self.widget_11.setGeometry(QtCore.QRect(0, 0, 731, 131))
        self.widget_11.setObjectName("widget_11")
        self.label_11 = QtWidgets.QLabel(self.widget_11)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_11.setObjectName("label_11")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_31.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.comboBox_31 = QtWidgets.QComboBox(self.widget_11)
        self.comboBox_31.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_32 = QtWidgets.QComboBox(self.widget_11)
        self.comboBox_32.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_32.setObjectName("comboBox_32")
        self.comboBox_33 = QtWidgets.QComboBox(self.widget_11)
        self.comboBox_33.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_33.setObjectName("comboBox_33")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_32.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_33.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_11.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.widget_12 = QtWidgets.QWidget(Form)
        self.widget_12.setGeometry(QtCore.QRect(30, 1740, 731, 131))
        self.widget_12.setObjectName("widget_12")
        self.label_12 = QtWidgets.QLabel(self.widget_12)
        self.label_12.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_12.setObjectName("label_12")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.widget_12)
        self.lineEdit_34.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.comboBox_34 = QtWidgets.QComboBox(self.widget_12)
        self.comboBox_34.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_34.setObjectName("comboBox_34")
        self.comboBox_35 = QtWidgets.QComboBox(self.widget_12)
        self.comboBox_35.setGeometry(QtCore.QRect(300, 40, 111, 22))
        self.comboBox_35.setObjectName("comboBox_35")
        self.comboBox_36 = QtWidgets.QComboBox(self.widget_12)
        self.comboBox_36.setGeometry(QtCore.QRect(20, 70, 111, 22))
        self.comboBox_36.setObjectName("comboBox_36")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget_12)
        self.lineEdit_35.setGeometry(QtCore.QRect(440, 40, 113, 20))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.widget_12)
        self.lineEdit_36.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_12.setGeometry(QtCore.QRect(630, 100, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "新增楼盘"))
        self.lineEdit.setText(_translate("Form", "房源编号"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.label_2.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_4.setText(_translate("Form", "房源编号2"))
        self.pushButton_2.setText(_translate("Form", "提交"))
        self.label_3.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_7.setText(_translate("Form", "房源编号3"))
        self.pushButton_3.setText(_translate("Form", "提交"))
        self.label_4.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_10.setText(_translate("Form", "房源编号4"))
        self.pushButton_4.setText(_translate("Form", "提交"))
        self.label_5.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_13.setText(_translate("Form", "房源编号5"))
        self.pushButton_5.setText(_translate("Form", "提交"))
        self.label_6.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_16.setText(_translate("Form", "房源编号6"))
        self.pushButton_6.setText(_translate("Form", "提交"))
        self.label_7.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_19.setText(_translate("Form", "房源编号7"))
        self.pushButton_7.setText(_translate("Form", "提交"))
        self.label_8.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_22.setText(_translate("Form", "房源编号8"))
        self.pushButton_8.setText(_translate("Form", "提交"))
        self.label_9.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_25.setText(_translate("Form", "房源编号9"))
        self.pushButton_9.setText(_translate("Form", "提交"))
        self.label_10.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_28.setText(_translate("Form", "房源编号"))
        self.pushButton_10.setText(_translate("Form", "提交"))
        self.label_11.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_31.setText(_translate("Form", "房源编号10"))
        self.pushButton_11.setText(_translate("Form", "提交"))
        self.label_12.setText(_translate("Form", "新增楼盘"))
        self.lineEdit_34.setText(_translate("Form", "房源编号11"))
        self.pushButton_12.setText(_translate("Form", "提交"))

